services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=ecomerce-api
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local

